print('한양은행 대출 상환금 계산 서비스에 오신걸 환영합니다.')
print('대출원금이 얼마인가요? (백만원이상 만)', end=' ')
debt=int(input())
print('상환기가은 몇 년인가요? (년 단위로)', end=' ')
year=int(input())
print('이자율은 몇% 인가요? (0.0에서 100.0 사이 수 만)', end=' ')
rate=float(input())
d=debt*rate*0.01/12*(1+rate*0.01/12)**(year*12)/((1+rate*0.01/12)**(year*12)-1)
d_m=int(d)
d_n=d_m*year*12
print('\n\n대출 상환금 내역을 알려드리겠습니다.')
print('대출원금:', debt, '원')
print('연 이자율', rate, '%로', year, '년 동안 매월 원리금 균등으로 상환')
print('매월', d_m, '원씩 지불하셔야 합니다.')
print('상환완료시까지 총 상환금액은', d_n, '원 입니다.\n')
print('저희 한양은행은 항상 여러분과 함께 합니다.')
print('또 들려주세요.')
