print('동전 합산 해줄께... 음수는 넣지마.')
print('오백원짜리 몇개?', end=' ')
fh=int(input())
print('백원짜리 몇개?', end=' ')
oh=int(input())
print('오십원짜리 몇개?', end=' ')
ft=int(input())
print('십원짜리 몇개?', end=' ')
ot=int(input())
print('자기가 갖고 있는 동전은 총', fh*500+oh*100+ft*50+ot*10, '원 이야.')
